language: node_js
node_js: 
  - node
cache: npm



install: 
  - npm install

script: 
  - npm test
  - npm run build

deploy: 
  rovider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: main